#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION=$(gh_releases cakephp/cakephp | tail -1)
FILENAME="cakephp-$(echo $VERSION | sed 's|\.|-|g').zip"
URL="https://github.com/cakephp/cakephp/releases/download/$VERSION/$FILENAME"

dl $URL /usr/local/src
