#!/bin/bash -ex

VERSION="2.3.1"
URL="https://github.com/cakephp/cakephp/tarball/$VERSION"

[ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
curl -L -f $PROXY $URL -o /usr/local/src/cakephp.tar.gz

