#!/bin/bash -ex

WEBROOT=/var/www/cakephp
# webroot dir created by cakephp composer install

# temporarily allow www-data write access to /var/www (only)
chown www-data /var/www # note not recursive

# set up turnkey-composer
sed -i "\|HOME_FALLBACK=|s|=.*|=/var/www/.composer|" /usr/local/bin/turnkey-composer
sed -i "\|APP_ROOT_FALLBACK=|s|=.*|=$WEBROOT|" /usr/local/bin/turnkey-composer
mkdir -p /var/www/.composer
chown -R www-data /var/www/.composer

# install cakephp app skeleton for TKL example app
APP_ROOT=/var/www turnkey-composer create-project --no-interaction --prefer-dist cakephp/app cakephp
# return root ownership of /var/www
chown root /var/www # note not recursive

mv /var/www/turnkey-shim.php "$WEBROOT"/templates/Pages/

# initial config
CONF=$WEBROOT/config/app_local.php
APP=cakephp
# disable debugging
sed -i "\|'DEBUG'|s|true|false|" $CONF

## DB setup
# CakePHP DB conf - 'my_app' is default DB and DB username - dirty but works...
sed -i "s|my_app|$APP|" $CONF

# Cake DB & user
systemctl start mariadb
mysqladmin create $APP
mysql --batch --execute "CREATE USER '$APP'@'localhost' IDENTIFIED BY 'initial_pass';"
mysql --batch --execute "GRANT ALL PRIVILEGES ON $APP.* TO '$APP'@'localhost';"
mysql --batch --execute "FLUSH PRIVILEGES;"

# use inithook to generate initial salt and set DB user password
/usr/lib/inithooks/firstboot.d/20regen-cakephp-secrets

# create default cakePHP DB tables
$WEBROOT/bin/cake migrations migrate

# send mail via local SMTP MTA (postfix)
sed -Ei "\
    /'EmailTransport'/,/'host' => 'localhost',/ \
    s|^([[:blank:]]*)('host' => 'localhost',)|\1'className' => SmtpTransport::class,\n\1\2| \
" $CONF

## set up TurnKey landing page
HOME=$WEBROOT/templates/Pages/home.php

# put landing page images in place
for img in adminer.png webmin.png; do
    mv /var/www/images/$img  $WEBROOT/webroot/img/
done
rm -r /var/www/{css,images,js}

# allow page to show with debug disabled
sed -i '\|!Configure::read|,+4 s|^|//|' $HOME

NEW_STR="Replace $HOME to see your own custom page here"
sed -i "\|<small>|s|>.*</|>$NEW_STR</|" $HOME

# insert custom TKL html (turnkey-shim.php in overlay)
sed -i "\|<small>|{n;a\<?php include 'turnkey-shim.php' ?>
}" $HOME

# turn on assertions to avoid cakephp warning
sed -i '/^zend\.assertions/ s|-1$|1|' /etc/php/8.?/{cli,apache2}/php.ini

chown www-data:www-data $CONF
chmod 640 $CONF

# configure apache
a2dissite 000-default
a2ensite cakephp
a2enmod rewrite
