#!/bin/sh -ex

DB_NAME=cakephp
DB_USER=cakephp
DB_PASS=$(mcookie)

SRC=/usr/local/src
WEBROOT=/var/www/cakephp

# unpack and set permissions
mkdir -p $WEBROOT
unzip -d $WEBROOT $SRC/cakephp.zip
rm $SRC/cakephp.zip
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/tmp

# tweak configuration
CONF=$WEBROOT/config/app.php

sed -i "\
    s#\\('salt' => \\)'.\\+'#\\1'$(mcookie)'#; \
    /Datasources/,/        \\],/{ \
        s#\\('username' => \\)'.*'#\\1'cakephp'#; \
        s#\\('database' => \\)'.*'#\\1'cakephp'#; \
        s#\\('password' => \\)'.*'#\\1'$DB_PASS'# \
    }; \
    /EmailTransport/,/    \\]/ \
        s#\\('className' => \\)'Mail'#\\1'Smtp'# \
" $CONF

chown www-data:www-data $CONF
chmod 640 $CONF

# setup the database
/etc/init.d/mysql start

MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

/etc/init.d/mysql stop

# configure apache
a2dissite 000-default
a2ensite cakephp
a2enmod rewrite

# setup tkl-webcp
mv /var/www/js/* $WEBROOT/webroot/js/; rm -rf /var/www/js
mv /var/www/css/* $WEBROOT/webroot/css/; rm -rf /var/www/css
mv /var/www/images/* $WEBROOT/webroot/img/; rm -rf /var/www/images

ln -s $WEBROOT/webroot/img $WEBROOT/webroot/images

cp -TdR $SRC/cakephp.overlay $WEBROOT
rm -rf $SRC/cakephp.overlay

