#!/bin/bash -ex

DB_NAME=cakephp
DB_USER=cakephp
DB_PASS=$(mcookie)

SRC=/usr/local/src
WEBROOT=/var/www/cakephp

# unpack and set permissions
mkdir -p $WEBROOT
unzip -d $WEBROOT $SRC/cakephp*.zip
rm $SRC/cakephp*.zip
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/tmp

# put landing page images in place
for img in adminer.png webmin.png; do
    mv /var/www/images/$img  $WEBROOT/webroot/img/
done
rm -r /var/www/{css,images,js}

# tweak configuration
CONF=$WEBROOT/config/app_local.php

sed -i "\
    s#\\('salt' => \\).*#\\1'$(mcookie)'#; \
    /Datasources/,/^    \\],/{ \
        s#\\('username' => \\)'.*'#\\1'cakephp'#; \
        s#\\('database' => \\)'.*'#\\1'cakephp'#; \
        s#\\('password' => \\)'.*'#\\1'$DB_PASS'# \
    }; \
    /EmailTransport/,/    \\]/ \
        s#\\('className' => \\)'Mail'#\\1'Smtp'# \
" $CONF
sed -i "\
	/Datasources/ { a\
\        'debug_kit' => [\n\
            'className' => 'Cake\\\\Database\\\\Connection',\n\
            'driver' => 'Cake\\\\Database\\\\Driver\\\\Mysql',\n\
            'persistent' => false,\n\
            'host' => 'localhost',\n\
            'port' => '3306',\n\
            'database' => 'cakephp',\n\
            'username' => 'cakephp',\n\
            'password' => '$DB_PASS',\n\
            'timezone' => 'UTC',\n\
            'flags' => [],\n\
            'log' => false,\n\
        ],\n\

	};" $CONF
sed -i "/DebugKit/,/<hr>/ {
    /<hr>/a\
            <?php include 'turnkey-shim.php' ?>
    };" /var/www/cakephp/templates/Pages/home.php

chown www-data:www-data $CONF
chmod 640 $CONF

# setup the database
service mysql start
mysqladmin create $DB_NAME
mysql --batch --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"
service mysql stop

# configure apache
a2dissite 000-default
a2ensite cakephp
a2enmod rewrite
