#!/bin/bash -e
# regenerate cakephp secrets and mysql password

. /etc/default/inithooks

CONF=/var/www/cakephp/config/app_local.php
sed -i "s#\\('salt' => \\).*#\\1'$(mcookie)'#" $CONF

PASSWORD=$(mcookie)
sed -i "\
    /Datasources/,/^    \\],/{ \
        s#\\('password' => \\)'.*'#\\1'$PASSWORD'# \
    }; \
" $CONF

$INITHOOKS_PATH/bin/mysqlconf.py --user=cakephp --pass="$PASSWORD"

