#!/bin/bash -e
# regenerate cakephp secrets and mysql password

. /etc/default/inithooks

CONF=/var/www/cakephp/config/app_local.php
salt=$(mcookie)$(mcookie)
sed -Ei "s|(SECURITY_SALT[' ,]+)[a-z0-9]*('.*)|\1$salt\2|" $CONF

PASSWORD=$(mcookie)
sed -i "\
    /Datasources/,/^    \\],/{ \
        s#\\('password' => \\)'.*'#\\1'$PASSWORD'# \
    }; \
" $CONF

"$INITHOOKS_PATH/bin/mysqlconf.py" --user=cakephp --pass="$PASSWORD"
